name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [14]
    name: Test Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        if: github.repository != 'anchan828/nest-lerna-template'
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          debug: true
